### ISSUE TITLE
ItemTypeAdapter 不支持 相同数据源,不同布局

### ISSUE THREAD

**Issue by open9527** [czy1121/rv#1]
ItemTypeAdapter 当使用相同数据源,不同布局UI的时候 是没效果的,

**Comment by czy1121** [comment]
你是怎么用的？一个Item类型在同一列表中映射多个布局，需要Item类实现ItemSubtype，然后创建ItemType实例时传入subtype

**Comment by open9527** [comment]
> 

嗯,是我这边 item 没有实现ItemSubtype,实现ItemSubtype 是可以 同数据源不同UI

但是我发现  多类型创建 bindingType 的subtype这个字段 如果是需要在item中获取的话,是不方便的


> 你是怎么用的？一个Item类型在同一列表中映射多个布局，需要Item类实现ItemSubtype，然后创建ItemType实例时传入subtype

**Comment by czy1121** [comment]
不明白你的需求。

这里提供了LayoutItemType和ViewItemType，如果不符合你的需求，你可以很轻松自己实现一个的
